version: 2

conda:
    environment: conda/environment.yml

sphinx:
  configuration: docs/conf.py

build:
    image: latest

python:
    install:
      - method: pip
        path: .
      #- method: setuptools        
        #This would do pip install .[docs] - if have a 'docs' dep in setup.py
        #extra_requirements:
           #- docs
  