version: 2

conda:
    environment: conda/environment.yml

sphinx:
  configuration: docs/conf.py

build:
    image: latest

python:
    install:
      - method: pip
        path: .
        extra_requirements:
         - docs
