version: 2

conda:
    environment: conda/environment.yml

sphinx:
  configuration: docs/conf.py

build:
    image: latest

#python:
    #version: 3.6
    #pip_install: true
    #setup_py_install: true    